version: 1
project_id: a86c2626-9cc1-4a55-957b-0701f6bb8101
default_environment: dev  # Add this line
environments:
- name: dev
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
      - entity: order_details
        path: ../../res/data/order_details.csv
        keys:
        - order_id
        - product_id
        - unit_price
        - quantity
        - discount
      state: enabled
      state_id_suffix: latest
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    config:
      host: localhost
      port: 5432
      database: northwind
      user: northwind_user
      state: enabled
      state_id_suffix: latest
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
    config:
      overwrite: 'false'
  - name: target-jsonl-csv
    inherit_from: target-jsonl
    config:
      destination_path: /data/csv/{table}/2025-01-31/{table}.jsonl
  - name: target-jsonl-postgres
    inherit_from: target-jsonl
  utilities:
  - name: airflow
    variant: apache
    pip_url: git+https://github.com/meltano/airflow-ext.git@main apache-airflow==2.8.1
      --constraint 
      https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/constraints-no-providers-${MELTANO__PYTHON_VERSION}.txt
jobs:
- name: csv-to-json
  tasks:
  - tap-csv target-jsonl-csv
- name: postgres-to-json
  tasks:
  - tap-postgres target-jsonl-postgres
schedules:
- name: daily-csv-to-json
  interval: '@daily'
  job: csv-to-json
- name: daily-postgres-to-json
  interval: '@daily'
  job: postgres-to-json
